name: Download

on: 
  push:
    branches: 
      - _master # build master branch only

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Download
      run: |
        mkdir download
        cd download
        mkdir re
        cd re
        curl -LJO ${{ secrets.LINK }}
        cd ..
        tar cjf - re/ |split -b 20m - dl.tar.bz2.
        echo "copy /b dl.tar.bz2.* dl.tar.bz2" > end.bat
        rm -rf re/
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./download
